In [1]:
import torch
import numpy as np

## initializing tensors

In [4]:
# from data directly
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [5]:
# from Numpy arrays
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [8]:
# from other tensors
x_ones = torch.zeros_like(x_data)
print(f"ones tenser: {x_ones}")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"random tensor: {x_rand}")

ones tenser: tensor([[0, 0],
        [0, 0]])
random tensor: tensor([[0.3156, 0.9458],
        [0.1077, 0.8758]])


In [10]:
# with random or constant values
shape = (2, 3, )
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"random tensor: {rand_tensor}")
print(f"ones tensor: {ones_tensor}")
print(f"zeros tensor: {zeros_tensor}")

random tensor: tensor([[0.1055, 0.7296, 0.6620],
        [0.5026, 0.7358, 0.0943]])
ones tensor: tensor([[1., 1., 1.],
        [1., 1., 1.]])
zeros tensor: tensor([[0., 0., 0.],
        [0., 0., 0.]])


## attributes: shape, dataytype, device

In [16]:
tensor = torch.rand(1, 2, 3, 4)

print(f"tensor: {tensor}")
print(f"shape: {tensor.shape}")
print(f"datatype: {tensor.dtype}")
print(f"device on: {tensor.device}")

tensor: tensor([[[[0.7498, 0.2633, 0.5299, 0.4705],
          [0.8707, 0.7004, 0.0858, 0.8661],
          [0.6931, 0.6941, 0.9231, 0.7968]],

         [[0.3501, 0.8215, 0.4948, 0.5249],
          [0.5372, 0.5106, 0.8876, 0.6173],
          [0.5341, 0.4471, 0.5304, 0.3584]]]])
shape: torch.Size([1, 2, 3, 4])
datatype: torch.float32
device on: cpu


## operations on tensors

In [17]:
# tensors are in CPU by default, use .to to change device
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

In [20]:
# index and slice
tensor = torch.ones(4, 3)
print("first row: ", tensor[0])
print("first column: ", tensor[:, 0])
print("last colum: ", tensor[..., -1])
tensor[:, 1] = 0
print(tensor)

first row:  tensor([1., 1., 1.])
first column:  tensor([1., 1., 1., 1.])
last colum:  tensor([1., 1., 1., 1.])
tensor([[1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.]])


In [22]:
# join
tensor_cat = torch.cat([tensor, tensor, tensor], dim=1)
print(tensor_cat.shape)
print(tensor_cat)

torch.Size([4, 9])
tensor([[1., 0., 1., 1., 0., 1., 1., 0., 1.],
        [1., 0., 1., 1., 0., 1., 1., 0., 1.],
        [1., 0., 1., 1., 0., 1., 1., 0., 1.],
        [1., 0., 1., 1., 0., 1., 1., 0., 1.]])


In [27]:
# arithmetic
## matrix multiply
matmul_1 = tensor @ tensor.T
matmul_2 = tensor.matmul(tensor.T)
matmul_3 = torch.zeros_like(tensor)
torch.matmul(tensor, tensor.T, out=matmul_3)
print(matmul_1)
print(matmul_2)
print(matmul_3)

## element-wise multiply
elemul_1 = tensor * tensor
elemul_2 = tensor.mul(tensor)
elemul_3 = torch.zeros_like(tensor)
torch.mul(tensor, tensor, out=elemul_3)
print(elemul_1)
print(elemul_2)
print(elemul_3)

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])
tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])
tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])
tensor([[1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.]])
tensor([[1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.]])
tensor([[1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.]])


In [28]:
# aggregate to single-element value
agg = tensor.sum()
agg_item = agg.item()
print(agg, type(agg))
print(agg_item, type(agg_item))

tensor(8.) <class 'torch.Tensor'>
8.0 <class 'float'>


In [31]:
# in-place: auto-increase/auto-decrease
print(tensor)
tensor.add_(6)
print(tensor)
tensor.sub_(2)
print(tensor)

tensor([[1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.]])
tensor([[7., 6., 7.],
        [7., 6., 7.],
        [7., 6., 7.],
        [7., 6., 7.]])
tensor([[5., 4., 5.],
        [5., 4., 5.],
        [5., 4., 5.],
        [5., 4., 5.]])


## bridge with NumPy

In [39]:
# tensor to array
t = torch.ones(2, 5)
print(t)
n = t.numpy()
print(n)

# sharing memory with in-place
t.add_(2)
print(t)
print(n)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
tensor([[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]])
[[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]


In [42]:
# array to tensor
n = np.ones((2, 5))
print(n)
t = torch.from_numpy(n)
print(t)

np.add(n, 2, out=n)
print(n)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)
